his_size: 50  # Number of sampled click history for each user
recent_size: 3
title_size: 30
abstract_size: 50
word_freq_threshold: 1
entity_size: 5

# dim
word_emb_dim: 300
category_emb_dim: 100
subcategory_emb_dim: 100
entity_emb_dim: 100
news_emb_dim: 400

bsarec:
  initializer_range: 0.2
  hidden_dropout_prob: 0.5
  attention_probs_dropout_prob: 0.5
  num_hidden_layers: 2
  alpha: 0.3
  c: 3

# For additive attention
attention_hidden_dim: 200
head_num: 20
head_dim: 20
word_filter_num: 0

use_graph: false
use_entity: false
num_neighbors: 10


use_neighbor_aggregation: false
k_neighbors: 5
similarity_threshold: 0.1
aggregation_method: "weighted_sum"
cache_size: 10000
cache_update_frequency: 10
neighbor_aggregation_weight: 0.3


